[package]
name = "cubular"
version = "0.1.0"
authors = ["tjjfvi <tjjfvi@tjjfvi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
lazy_static = "1.4.0"
